//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rules.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rules.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a noreply@cordoba.gob.ar.
        /// </summary>
        internal static string mail_emisor_direccion {
            get {
                return ResourceManager.GetString("mail_emisor_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #CBA147 Municipalidad de Córdoba.
        /// </summary>
        internal static string mail_emisor_nombre {
            get {
                return ResourceManager.GetString("mail_emisor_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://play.google.com/store/apps/details?id=com.cordoba.
        /// </summary>
        internal static string url_app_android {
            get {
                return ResourceManager.GetString("url_app_android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://itunes.apple.com/ar/app/cba147/id1349553071.
        /// </summary>
        internal static string url_app_ios {
            get {
                return ResourceManager.GetString("url_app_ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.facebook.com/municba.
        /// </summary>
        internal static string url_facebook {
            get {
                return ResourceManager.GetString("url_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://res.cloudinary.com/dxrej9loi/image/upload/v1507306902/icono-logo-cba-147_tkptrp.png.
        /// </summary>
        internal static string url_imagen_cba147 {
            get {
                return ResourceManager.GetString("url_imagen_cba147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://res.cloudinary.com/dxrej9loi/image/upload/v1507306902/logo_muni_vql2gs.png.
        /// </summary>
        internal static string url_imagen_muni {
            get {
                return ResourceManager.GetString("url_imagen_muni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.instagram.com/municba.
        /// </summary>
        internal static string url_instagram {
            get {
                return ResourceManager.GetString("url_instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.cordoba.gob.ar/.
        /// </summary>
        internal static string url_muni {
            get {
                return ResourceManager.GetString("url_muni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://twitter.com/municba.
        /// </summary>
        internal static string url_twitter {
            get {
                return ResourceManager.GetString("url_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://servicios2.cordoba.gov.ar/CBA147.
        /// </summary>
        internal static string url_web {
            get {
                return ResourceManager.GetString("url_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.youtube.com/user/cordobagovar.
        /// </summary>
        internal static string url_youtube {
            get {
                return ResourceManager.GetString("url_youtube", resourceCulture);
            }
        }
    }
}
