//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos_Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos_Login() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.Recursos_Login", typeof(Recursos_Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Boton_Contacto {
            get {
                return ResourceManager.GetString("Boton_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar usuario.
        /// </summary>
        internal static string Boton_CrearUsuario {
            get {
                return ResourceManager.GetString("Boton_CrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string Boton_IniciarSesion {
            get {
                return ResourceManager.GetString("Boton_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Politica de privacidad.
        /// </summary>
        internal static string Boton_PoliticaPrivacidad {
            get {
                return ResourceManager.GetString("Boton_PoliticaPrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Politica de seguridad.
        /// </summary>
        internal static string Boton_PoliticaSeguridad {
            get {
                return ResourceManager.GetString("Boton_PoliticaSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidó su contraseña?.
        /// </summary>
        internal static string Boton_RecuperarCuenta {
            get {
                return ResourceManager.GetString("Boton_RecuperarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Términos y condiciones de uso.
        /// </summary>
        internal static string Boton_TerminosCondiciones {
            get {
                return ResourceManager.GetString("Boton_TerminosCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido a #CBA147! Es una plataforma de atención al vecino que nos permite mejorar la ciudad de manera colaborativa. Cargá tus requerimientos y solicitudes sin moverte de tu casa conociendo el grado de avance..
        /// </summary>
        internal static string Texto_InfoCBA147_Texto {
            get {
                return ResourceManager.GetString("Texto_InfoCBA147_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué es #CBA147?.
        /// </summary>
        internal static string Texto_InfoCBA147_Titulo {
            get {
                return ResourceManager.GetString("Texto_InfoCBA147_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string Texto_IniciarSesion {
            get {
                return ResourceManager.GetString("Texto_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tiene cuenta? &gt;&gt;&gt;.
        /// </summary>
        internal static string Texto_NoTieneCuenta {
            get {
                return ResourceManager.GetString("Texto_NoTieneCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su usuario no se encuentra activado. .
        /// </summary>
        internal static string Texto_Usuario_NoActivado {
            get {
                return ResourceManager.GetString("Texto_Usuario_NoActivado", resourceCulture);
            }
        }
    }
}
