//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internet_UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos_RequerimientoNuevo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos_RequerimientoNuevo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Internet_UI.Resources.Recursos_RequerimientoNuevo", typeof(Recursos_RequerimientoNuevo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string Boton_Anterior {
            get {
                return ResourceManager.GetString("Boton_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string Boton_Siguiente {
            get {
                return ResourceManager.GetString("Boton_Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llegaste al último paso. Hacé clic en la casilla “No soy un robot” para validar tu requerimiento. Apretá “REGISTRAR”..
        /// </summary>
        internal static string Texto_Descripcion_Confirmacion {
            get {
                return ResourceManager.GetString("Texto_Descripcion_Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Describi de manera clara y concisa tu inconveniente y luego presioná &quot;SIGUIENTE&quot;.
        /// </summary>
        internal static string Texto_Descripcion_Descripcion {
            get {
                return ResourceManager.GetString("Texto_Descripcion_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si querés, adjuntá una foto del requerimiento. Este paso es opcional..
        /// </summary>
        internal static string Texto_Descripcion_Foto {
            get {
                return ResourceManager.GetString("Texto_Descripcion_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este es el primer paso para registrar un requerimiento. A continuación elegí un servicio, luego seleccioná el motivo y presioná &quot;SIGUIENTE&quot;..
        /// </summary>
        internal static string Texto_Descripcion_Tipo {
            get {
                return ResourceManager.GetString("Texto_Descripcion_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre de la calle, no es necesario que la escriba de manera completa, luego escribí la altura..
        /// </summary>
        internal static string Texto_Descripcion_Ubicacion {
            get {
                return ResourceManager.GetString("Texto_Descripcion_Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa o selecciona la ubicación.
        /// </summary>
        internal static string Texto_Descripcion_Ubicacion_Mobile {
            get {
                return ResourceManager.GetString("Texto_Descripcion_Ubicacion_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registrando el requerimiento.
        ///Detalle: {0}
        ///
        ///Por favor intente nuevamente..
        /// </summary>
        internal static string Texto_Error_Registrando_ConDetalle {
            get {
                return ResourceManager.GetString("Texto_Error_Registrando_ConDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registrando el requerimiento.
        ///Por favor intente nuevamente..
        /// </summary>
        internal static string Texto_Error_Registrando_SinDetalle {
            get {
                return ResourceManager.GetString("Texto_Error_Registrando_SinDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requerimiento registrado correctamente.
        ///Número: &lt;b&gt;{0}&lt;/b&gt;
        ///Te enviamos un e-mail a tu casilla de correo con el comprobante de la operación..
        /// </summary>
        internal static string Texto_RegistradoCorrectamente_ConEmail {
            get {
                return ResourceManager.GetString("Texto_RegistradoCorrectamente_ConEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requerimiento registrado correctamente.
        ///Número: &lt;b&gt;{0}&lt;/b&gt;
        ///
        ///No se puso enviar  por e-mail el comprobante de la operación. Por favor revisá la dirección de e-mail asociada a tu cuenta..
        /// </summary>
        internal static string Texto_RegistradoCorrectamente_SinEmail {
            get {
                return ResourceManager.GetString("Texto_RegistradoCorrectamente_SinEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        internal static string Texto_Titulo_Confirmacion {
            get {
                return ResourceManager.GetString("Texto_Titulo_Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Texto_Titulo_Descripcion {
            get {
                return ResourceManager.GetString("Texto_Titulo_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto.
        /// </summary>
        internal static string Texto_Titulo_Foto {
            get {
                return ResourceManager.GetString("Texto_Titulo_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Requerimiento.
        /// </summary>
        internal static string Texto_Titulo_NuevoRequerimiento {
            get {
                return ResourceManager.GetString("Texto_Titulo_NuevoRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Texto_Titulo_Tipo {
            get {
                return ResourceManager.GetString("Texto_Titulo_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string Texto_Titulo_Ubicacion {
            get {
                return ResourceManager.GetString("Texto_Titulo_Ubicacion", resourceCulture);
            }
        }
    }
}
